# Configuraci칩n de an치lisis est치tico de c칩digo
# Define las reglas de linting para el proyecto

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Errores
    avoid_print: true
    avoid_returning_null_for_void: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true

    # Estilo
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    # Convertir algunos warnings en errores
    invalid_annotation_target: ignore

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
